repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: lint
        name: 'lint'
        entry: bundle exec rake rubocop
        language: system
        description: "Lint"
        pass_filenames: false
      - id: test
        name: 'test'
        entry: bundle exec rake spec
        language: system
        description: "Test"
        pass_filenames: false
