# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataEntry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sharepubapi_v1.DataEntry" do
    optional :type, :enum, 1, "sharepubapi_v1.DataEntry.Type"
    optional :value, :bytes, 2
  end
  add_enum "sharepubapi_v1.DataEntry.Type" do
    value :UNDEFINED, 0
    value :INVOICE, 1
    value :PAYMENT_TRANSACTION, 2
    value :LOCATION, 3
    value :TRANSACTION, 4
    value :AGE_VERIFICATION_SECRET, 5
    value :THIRD_PARTY_ATTRIBUTE, 6
  end
end

module Yoti
  module Protobuf
    module Sharepubapi
      DataEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("sharepubapi_v1.DataEntry").msgclass
      DataEntry::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("sharepubapi_v1.DataEntry.Type").enummodule
    end
  end
end
