# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto

require 'google/protobuf'

require_relative 'DataEntry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sharepubapi_v1.ExtraData" do
    repeated :list, :message, 1, "sharepubapi_v1.DataEntry"
  end
end

module Yoti
  module Protobuf
    module Sharepubapi
      ExtraData = Google::Protobuf::DescriptorPool.generated_pool.lookup("sharepubapi_v1.ExtraData").msgclass
    end
  end
end
