# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdPartyAttribute.proto

require 'google/protobuf'

require_relative 'IssuingAttributes_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sharepubapi_v1.ThirdPartyAttribute" do
    optional :issuance_token, :bytes, 1
    optional :issuing_attributes, :message, 2, "sharepubapi_v1.IssuingAttributes"
  end
end

module Yoti
  module Protobuf
    module Sharepubapi
      ThirdPartyAttribute = Google::Protobuf::DescriptorPool.generated_pool.lookup("sharepubapi_v1.ThirdPartyAttribute").msgclass
    end
  end
end
