# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list.proto

require 'google/protobuf'

require_relative 'Attribute_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Yoti.Protobuf.attrpubapi_v3.AttributeAndId" do
    optional :attribute, :message, 1, "Yoti.Protobuf.attrpubapi_v3.Attribute"
    optional :attribute_id, :bytes, 2
  end
  add_message "Yoti.Protobuf.attrpubapi_v3.AttributeAndIdList" do
    repeated :attribute_and_id_list, :message, 1, "Yoti.Protobuf.attrpubapi_v3.AttributeAndId"
  end
  add_message "Yoti.Protobuf.attrpubapi_v3.AttributeList" do
    repeated :attributes, :message, 1, "Yoti.Protobuf.attrpubapi_v3.Attribute"
  end
end

module Yoti
  module Protobuf
    module AttrpubapiV3
      AttributeAndId = Google::Protobuf::DescriptorPool.generated_pool.lookup("Yoti.Protobuf.attrpubapi_v3.AttributeAndId").msgclass
      AttributeAndIdList = Google::Protobuf::DescriptorPool.generated_pool.lookup("Yoti.Protobuf.attrpubapi_v3.AttributeAndIdList").msgclass
      AttributeList = Google::Protobuf::DescriptorPool.generated_pool.lookup("Yoti.Protobuf.attrpubapi_v3.AttributeList").msgclass
    end
  end
end
