version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    target_branch: "development"

    default_reviewers:
      - "echarrod"
      - "davidgrayston"
      - "emmas-yoti"
      - "MrBurtyyy"
