# frozen_string_literal: true

module Yoti
  module DocScan
    class Constants
      ID_DOCUMENT_AUTHENTICITY = 'ID_DOCUMENT_AUTHENTICITY'
      ID_DOCUMENT_TEXT_DATA_CHECK = 'ID_DOCUMENT_TEXT_DATA_CHECK'
      ID_DOCUMENT_FACE_MATCH = 'ID_DOCUMENT_FACE_MATCH'
      LIVENESS = 'LIVENESS'
      ID_DOCUMENT_TEXT_DATA_EXTRACTION = 'ID_DOCUMENT_TEXT_DATA_EXTRACTION'
      ID_DOCUMENT = 'ID_DOCUMENT'
      ORTHOGONAL_RESTRICTIONS = 'ORTHOGONAL_RESTRICTIONS'
      DOCUMENT_RESTRICTIONS = 'DOCUMENT_RESTRICTIONS'
      INCLUSION_WHITELIST = 'WHITELIST'
      INCLUSION_BLACKLIST = 'BLACKLIST'
    end
  end
end
