# frozen_string_literal: true

module Yoti
  module DocScan
    class Constants
      ID_DOCUMENT_AUTHENTICITY = 'ID_DOCUMENT_AUTHENTICITY'
      ID_DOCUMENT_COMPARISON = 'ID_DOCUMENT_COMPARISON'
      ID_DOCUMENT_TEXT_DATA_CHECK = 'ID_DOCUMENT_TEXT_DATA_CHECK'
      SUPPLEMENTARY_DOCUMENT_TEXT_DATA_CHECK = 'SUPPLEMENTARY_DOCUMENT_TEXT_DATA_CHECK'
      ID_DOCUMENT_FACE_MATCH = 'ID_DOCUMENT_FACE_MATCH'
      LIVENESS = 'LIVENESS'
      ID_DOCUMENT_TEXT_DATA_EXTRACTION = 'ID_DOCUMENT_TEXT_DATA_EXTRACTION'
      SUPPLEMENTARY_DOCUMENT_TEXT_DATA_EXTRACTION = 'SUPPLEMENTARY_DOCUMENT_TEXT_DATA_EXTRACTION'
      ID_DOCUMENT = 'ID_DOCUMENT'
      SUPPLEMENTARY_DOCUMENT = 'SUPPLEMENTARY_DOCUMENT'
      ORTHOGONAL_RESTRICTIONS = 'ORTHOGONAL_RESTRICTIONS'
      DOCUMENT_RESTRICTIONS = 'DOCUMENT_RESTRICTIONS'
      INCLUDE = 'WHITELIST'
      EXCLUDE = 'BLACKLIST'
      ALWAYS = 'ALWAYS'
      FALLBACK = 'FALLBACK'
      DESIRED = 'DESIRED'
      IGNORE = 'IGNORE'
      NEVER = 'NEVER'
      ZOOM = 'ZOOM'
      CAMERA = 'CAMERA'
      CAMERA_AND_UPLOAD = 'CAMERA_AND_UPLOAD'
      RESOURCE_UPDATE = 'RESOURCE_UPDATE'
      TASK_COMPLETION = 'TASK_COMPLETION'
      CHECK_COMPLETION = 'CHECK_COMPLETION'
      SESSION_COMPLETION = 'SESSION_COMPLETION'
      PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS'
      THIRD_PARTY_IDENTITY = 'THIRD_PARTY_IDENTITY'
    end
  end
end
