source 'https://rubygems.org'

gem 'dotenv-rails'
gem 'puma', '~> 4.0'
gem 'rails', '~> 5.2.4', '>= 5.2.4.3'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'yoti', path: '../..'
