# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "attrpubapi_v1.ContentType" do
    value :UNDEFINED, 0
    value :STRING, 1
    value :JPEG, 2
    value :DATE, 3
    value :PNG, 4
    value :JSON, 5
    value :MULTI_VALUE, 6
    value :INT, 7
  end
end

module Yoti
  module Protobuf
    module Attrpubapi
      ContentType = Google::Protobuf::DescriptorPool.generated_pool.lookup("attrpubapi_v1.ContentType").enummodule
    end
  end
end
