# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto

require 'google/protobuf'

require 'Attribute_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "attrpubapi_v1.AttributeAndId" do
    optional :attribute, :message, 1, "attrpubapi_v1.Attribute"
    optional :attribute_id, :bytes, 2
  end
  add_message "attrpubapi_v1.AttributeAndIdList" do
    repeated :attribute_and_id_list, :message, 1, "attrpubapi_v1.AttributeAndId"
  end
  add_message "attrpubapi_v1.AttributeList" do
    repeated :attributes, :message, 1, "attrpubapi_v1.Attribute"
  end
end

module Yoti
  module Protobuf
    module Attrpubapi
      AttributeAndId = Google::Protobuf::DescriptorPool.generated_pool.lookup("attrpubapi_v1.AttributeAndId").msgclass
      AttributeAndIdList = Google::Protobuf::DescriptorPool.generated_pool.lookup("attrpubapi_v1.AttributeAndIdList").msgclass
      AttributeList = Google::Protobuf::DescriptorPool.generated_pool.lookup("attrpubapi_v1.AttributeList").msgclass
    end
  end
end
