# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signing.proto

require 'google/protobuf'

require 'ContentType_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "attrpubapi_v1.AttributeSigning" do
    optional :name, :string, 1
    optional :value, :bytes, 2
    optional :content_type, :enum, 3, "attrpubapi_v1.ContentType"
    optional :artifact_signature, :bytes, 4
    optional :sub_type, :string, 5
    optional :signed_time_stamp, :bytes, 6
  end
end

module Yoti
  module Protobuf
    module Attrpubapi
      AttributeSigning = Google::Protobuf::DescriptorPool.generated_pool.lookup("attrpubapi_v1.AttributeSigning").msgclass
    end
  end
end
