name: Unit Tests
on: [push, pull_request_target]

jobs:
  rake:
    name: Rake (Ruby ${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' || # always run on push events
      github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository # only run on pull_request_target event when pull request pulls from fork repository
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7, 2.6, 2.5, 2.4]

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1.57.0
        with:
          bundler: Gemfile.lock
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}

      - run: bundle exec rake test
