# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EncryptedData.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "compubapi_v1.EncryptedData" do
    optional :iv, :bytes, 1
    optional :cipher_text, :bytes, 2
  end
end

module Yoti
  module Protobuf
    module Compubapi
      EncryptedData = Google::Protobuf::DescriptorPool.generated_pool.lookup("compubapi_v1.EncryptedData").msgclass
    end
  end
end
